import arcade

#VIEW PROPS
APP_TITLE = f"Simple game"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
LEFT_VIEWPORT_MARGIN = 250
RIGHT_VIEWPORT_MARGIN = 250
BOTTOM_VIEWPORT_MARGIN = 50
TOP_VIEWPORT_MARGIN = 100


#Game props
BACKGROUND = arcade.csscolor.CORNFLOWER_BLUE
TILE_SCALE = 1  
COIN_SCALE = 1

#Character props
VIEW_DISTANCE = 200
CHARACTER_SCALE = 1
MOVEMENT_SPEED = 4
JUMP_HEIGHT = 15
GRAVITY = 0.8
RIGHT_FACING = 0
LEFT_FACING = 1

#Test objects
coordinate_list = [[512, 96],[256, 96],[768, 96]]